apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: python-img
          image: gcr.io/iti-mariam/python-img:latest
          env:
            - name: REDIS_HOST
              value: service-redis
          ports:
            - containerPort: 8000
